version: 2

sources:
  - name: subscription
    database: SUBSCRIPTION
    schema: RAW
    loader: daily_load_task
    loaded_at_field: _loaded_at
    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: account
        identifier: ACCOUNT
        columns:
            - name: ID
              tests:
                - unique
                - not_null            
            - name: NAME
            - name: STATE
            - name: CITY
            - name: DELETED_AT
            - name: _LOADED_AT

      - name: order
        identifier: ORDER
        quoting:
            identifier: true
        columns:
            - name: ID
              tests:
                - unique
                - not_null
            - name: CUSTOMER
              tests:
                - relationships:
                    to: source('subscription','account')
                    field: ID            
            - name: EFFECTIVE_ON
            - name: BOOKED_ON
            - name: TYPE
            - name: DELETED_AT
            - name: _LOADED_AT

      - name: order_product
        identifier: ORDER_PRODUCT
        columns:
            - name: ID
              tests:
                - unique
                - not_null            
            - name: ORDER_ID
              tests:
                - relationships:
                    to: source('subscription','order')
                    field: ID            
            - name: PRODUCT_ID
              tests:
                - relationships:
                    to: source('subscription','product')
                    field: ID            
            - name: QUANTITY_CHANGE
            - name: DELETED_AT
            - name: _LOADED_AT

      - name: product
        identifier: PRODUCT
        columns:
            - name: ID
              tests:
                - unique
                - not_null            
            - name: NAME
            - name: UNIT
            - name: UNIT_RATE
            - name: TYPE
            - name: UNIT_TIMING
            - name: STATUS
            - name: DELETED_AT
            - name: _LOADED_AT